name: flutter_magnifier_lens
description: "A highly customizable magnifying glass widget for Flutter."
version: 1.0.5
homepage: https://github.com/NeKoFu/flutter_magnifier_lens
license: MIT

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/lens.frag
